// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABmE1Xo_-AshxnD96HGrFEABI6afn6XVk',
    appId: '1:331202908149:web:7d485982bdf20371199abc',
    messagingSenderId: '331202908149',
    projectId: 'pokedex-7ba29',
    authDomain: 'pokedex-7ba29.firebaseapp.com',
    databaseURL: 'https://pokedex-7ba29-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-7ba29.appspot.com',
    measurementId: 'G-SB5EE0NBTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1XaalPmFPRCNDjFYY5vkFEazj2QnSZRk',
    appId: '1:331202908149:android:1c772647afde6143199abc',
    messagingSenderId: '331202908149',
    projectId: 'pokedex-7ba29',
    databaseURL: 'https://pokedex-7ba29-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-7ba29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfua0M5i-2RjVsUWGCyNl_ezQsL47T14w',
    appId: '1:331202908149:ios:65334d3006d64c2c199abc',
    messagingSenderId: '331202908149',
    projectId: 'pokedex-7ba29',
    databaseURL: 'https://pokedex-7ba29-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-7ba29.appspot.com',
    iosClientId: '331202908149-ijue2drish84qs4lf3249o7oaai4dh7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfua0M5i-2RjVsUWGCyNl_ezQsL47T14w',
    appId: '1:331202908149:ios:65334d3006d64c2c199abc',
    messagingSenderId: '331202908149',
    projectId: 'pokedex-7ba29',
    databaseURL: 'https://pokedex-7ba29-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-7ba29.appspot.com',
    iosClientId: '331202908149-ijue2drish84qs4lf3249o7oaai4dh7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPokedex',
  );
}
